# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibanaccount',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8d860c35-c17e-4dfb-bb6f-6de853b4f730'), editable=False),
        ),
    ]
