# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iban', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ibanaccount',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'IBAN accounts'},
        ),
        migrations.AlterField(
            model_name='ibanaccount',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3aac613a-37a3-4802-be2a-7249563acd2d'), editable=False),
        ),
    ]
