# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iban', '0002_auto_20180303_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibanaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ibanaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ibanaccount',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4a0fdf0c-5a99-4b83-8146-7e81061a845a'), editable=False),
        ),
    ]
