# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.generic.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iban', '0002_auto_20180227_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ibanaccount',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='ibanaccount',
            name='iban',
            field=localflavor.generic.models.IBANField(include_countries=None, max_length=34, use_nordea_extensions=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='ibanaccount',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e5b24d83-fb9e-4db2-8c55-2189e2719a1b'), editable=False),
        ),
    ]
